"""Exact finite-dimensional Grassmann algebra over rational coefficients.

An element of the algebra generated by anticommuting generators ``theta_0 .. theta_{n-1}``
is stored as a dict mapping *canonical monomials* -- strictly increasing tuples of
generator indices -- to nonzero ``Fraction`` coefficients. The empty tuple is the
scalar (body) part. All arithmetic is exact: products anticommute-sort with the
inversion-count sign, ``theta_i^2 = 0`` kills any monomial with a repeated index, and
``exp``/``log`` are the terminating nilpotent series.

No floating point anywhere. sympy is deliberately not used.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Iterable, Mapping

Monomial = tuple[int, ...]


def _merge_sign(a: Monomial, b: Monomial) -> tuple[Monomial, int]:
    """Concatenate two canonical monomials into canonical form with the fermionic sign.

    The sign is ``(-1)^inversions`` where ``inversions`` counts the transpositions
    needed to interleave the (already sorted) ``b`` into ``a``. A repeated generator
    yields sign 0 (``theta^2 = 0``).
    """
    if not a:
        return b, 1
    if not b:
        return a, 1
    merged: list[int] = []
    i = j = 0
    inversions = 0
    la = len(a)
    while i < la and j < len(b):
        if a[i] == b[j]:
            return (), 0
        if a[i] < b[j]:
            merged.append(a[i])
            i += 1
        else:
            # b[j] jumps over the remaining la - i elements of a
            inversions += la - i
            merged.append(b[j])
            j += 1
    merged.extend(a[i:])
    merged.extend(b[j:])
    return tuple(merged), (1 if inversions % 2 == 0 else -1)


class G:
    """A Grassmann-algebra element with exact rational coefficients."""

    __slots__ = ("terms",)

    def __init__(self, terms: Mapping[Monomial, Fraction | int] | None = None):
        self.terms: dict[Monomial, Fraction] = {}
        if terms:
            for mono, coeff in terms.items():
                c = Fraction(coeff)
                if c:
                    self.terms[tuple(mono)] = c

    # -- constructors ---------------------------------------------------------------

    @classmethod
    def scalar(cls, c: Fraction | int) -> "G":
        return cls({(): Fraction(c)})

    @classmethod
    def monomial(cls, gens: Iterable[int], coeff: Fraction | int = 1) -> "G":
        """Element ``coeff * theta_{g0} theta_{g1} ...`` in the *given* order.

        The order is honoured: an out-of-order sequence is anticommute-sorted and
        contributes the corresponding sign; repeated generators give zero.
        """
        out: Monomial = ()
        sign = 1
        for g in gens:
            out, s = _merge_sign(out, (int(g),))
            sign *= s
            if sign == 0:
                return cls()
        return cls({out: Fraction(coeff) * sign})

    # -- ring operations ------------------------------------------------------------

    def __add__(self, other: "G | int | Fraction") -> "G":
        other = _coerce(other)
        out = dict(self.terms)
        for mono, c in other.terms.items():
            s = out.get(mono, Fraction(0)) + c
            if s:
                out[mono] = s
            else:
                out.pop(mono, None)
        res = G()
        res.terms = out
        return res

    __radd__ = __add__

    def __neg__(self) -> "G":
        res = G()
        res.terms = {m: -c for m, c in self.terms.items()}
        return res

    def __sub__(self, other: "G | int | Fraction") -> "G":
        return self + (-_coerce(other))

    def __rsub__(self, other: "G | int | Fraction") -> "G":
        return _coerce(other) + (-self)

    def __mul__(self, other: "G | int | Fraction") -> "G":
        if isinstance(other, (int, Fraction)):
            res = G()
            f = Fraction(other)
            if f:
                res.terms = {m: c * f for m, c in self.terms.items()}
            return res
        out: dict[Monomial, Fraction] = {}
        for ma, ca in self.terms.items():
            for mb, cb in other.terms.items():
                mono, sign = _merge_sign(ma, mb)
                if sign == 0:
                    continue
                c = out.get(mono, Fraction(0)) + ca * cb * sign
                if c:
                    out[mono] = c
                else:
                    out.pop(mono, None)
        res = G()
        res.terms = out
        return res

    def __rmul__(self, other: "int | Fraction") -> "G":
        # scalars commute with everything
        return self * other

    def __eq__(self, other: object) -> bool:
        if isinstance(other, (int, Fraction)):
            other = _coerce(other)
        if not isinstance(other, G):
            return NotImplemented
        return self.terms == other.terms

    def __hash__(self):
        return hash(frozenset(self.terms.items()))

    def __bool__(self) -> bool:
        return bool(self.terms)

    # -- structure ------------------------------------------------------------------

    @property
    def scalar_part(self) -> Fraction:
        return self.terms.get((), Fraction(0))

    def body_free(self) -> "G":
        """The element minus its scalar part (the nilpotent 'soul')."""
        res = G()
        res.terms = {m: c for m, c in self.terms.items() if m}
        return res

    def degree_part(self, k: int) -> "G":
        res = G()
        res.terms = {m: c for m, c in self.terms.items() if len(m) == k}
        return res

    def max_degree(self) -> int:
        return max((len(m) for m in self.terms), default=0)

    def is_even(self) -> bool:
        return all(len(m) % 2 == 0 for m in self.terms)

    def __repr__(self) -> str:
        if not self.terms:
            return "G(0)"
        parts = []
        for mono in sorted(self.terms, key=lambda m: (len(m), m)):
            parts.append(f"{self.terms[mono]}*t{list(mono)}")
        return "G(" + " + ".join(parts) + ")"


def _coerce(x: "G | int | Fraction") -> G:
    if isinstance(x, G):
        return x
    return G.scalar(x)


# -- exp / log of nilpotent arguments ---------------------------------------------


def exp(x: G) -> G:
    """``exp(x)`` for ``x`` with zero scalar part (nilpotent): the series terminates.

    ``x`` need not be even; the series is well defined for any nilpotent element,
    though only even ``x`` gives the usual commuting-factor picture.
    """
    if x.scalar_part != 0:
        raise ValueError("exp requires zero scalar part (nilpotent argument)")
    result = G.scalar(1)
    power = G.scalar(1)
    k = 0
    fact = 1
    while True:
        power = power * x
        if not power:
            break
        k += 1
        fact *= k
        result = result + power * Fraction(1, fact)
    return result


def log(x: G) -> G:
    """``log(x)`` for ``x`` with scalar part exactly 1, via the nilpotent series
    ``log(1+n) = sum_k (-1)^(k+1) n^k / k`` which terminates."""
    if x.scalar_part != 1:
        raise ValueError(
            f"log requires scalar part 1 (got {x.scalar_part}); normalize the local "
            "factor first -- for a unique-jump table this means the fully occupied "
            "state must map to itself with sign +1"
        )
    n = x.body_free()
    result = G()
    power = G.scalar(1)
    k = 0
    while True:
        power = power * n
        if not power:
            break
        k += 1
        result = result + power * Fraction((-1) ** (k + 1), k)
    return result
